[performance-tuning]
= Performance Tuning

> linux & java processor
> apt-get update && apt-get install net-tools


== Command exec
1. for dir in ./*; do (cd "$dir" && pwd && gf && gup); done
2. find . -type d -name .git -exec sh -c "cd \"{}\"/../ && pwd && git pull" \;
** https://www.coder.work/article/2569962

== netstat

1. https://backstage.forgerock.com/knowledge/kb/article/a75965340[Best practice for JVM Tuning with G1 GC(Last updated Nov 2, 2020)]
1. netstat -ant | grep 8084 | awk '{print $6}' | sort | uniq -c
1. netstat -nat | grep ESTABLISHED | awk '{print $5}' | awk -F ':' '{print $1}' | sort | uniq -c
1. netstat -nat |grep 8084| grep ESTABLISHED | awk '{print $5}' | awk -F ':' '{print $1}' | sort | uniq -c

netstat -n | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}'

jstack 48626 | grep "cpu=" | awk '{print $1}' | awk -F '-' '{$NF="";print $0}' | sort | uniq -c

== jstack 

1. jstack 48626 | grep "java.lang.Thread.State" | awk '{$1=""; print $0}' | sort | uniq -c

ps -eTo stat,pid,tid,ppid,comm  | awk '{print $1}' | sort | uniq -c

== Arthas

> curl -O https://arthas.aliyun.com/arthas-boot.jar && java -jar arthas-boot.jar

1. 





echo 'net.core.wmem_max=16777216' >> /etc/sysctl.conf; \
echo 'net.core.rmem_max=16777216' >> /etc/sysctl.conf; \
echo 'net.ipv4.tcp_wmem=16777216' >> /etc/sysctl.conf; \
echo 'net.ipv4.tcp_tw_reuse=1' >> /etc/sysctl.conf; \
echo 'net.ipv4.tcp_low_latency=1' >> /etc/sysctl.conf; \
echo 'net.ipv4.tcp_limit_output_bytes=131072' >> /etc/sysctl.conf




-H 'Connection: Keep-Alive' -H 'Keep-Alive: timeout=5, max=1000'
ab -k  -n 1000000 -c 500 -p post_data_null.json -T "application/json" http://172.19.160.48:8080/api-x/trade/order/test
ab -k  -n 1000000 -c 500 -p post_data_null.json -T "application/json" http://172.19.160.48:8080/api-x/trade/order/test


net.core.wmem_max=16777216
net.core.rmem_max=16777216
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_low_latency=1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_max_tw_buckets= 15000 
net.ipv4.tcp_limit_output_bytes=131072
net.ipv4.tcp_rmem= 4096 65536 16777216
net.ipv4.tcp_wmem= 4096 87380 16777216



fs.file-max = 655360
kernel.msgmax = 65536
kernel.msgmnb = 65536
kernel.shmall = 4294967296
kernel.shmmax = 68719476736
kernel.sysrq = 0
net.core.netdev_max_backlog = 262144
net.core.rmem_default = 8388608
net.core.rmem_max=16777216
net.core.somaxconn = 262144
net.core.wmem_default = 8388608
net.core.wmem_max=16777216
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.tunl0.rp_filter=0
net.ipv4.ip_forward = 1
net.ipv4.ip_local_port_range = 2048 65000
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_intvl = 15
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.tcp_keepalive_time = 90
net.ipv4.tcp_limit_output_bytes=131072
net.ipv4.tcp_low_latency=1
net.ipv4.tcp_max_orphans = 3276800
net.ipv4.tcp_max_syn_backlog = 262144
net.ipv4.tcp_max_tw_buckets = 655350
net.ipv4.tcp_max_tw_buckets= 15000
net.ipv4.tcp_mem = 94500000 915000000 927000000
net.ipv4.tcp_rmem= 4096 65536 16777216
net.ipv4.tcp_sack = 1
net.ipv4.tcp_syn_retries = 1
net.ipv4.tcp_synack_retries = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_wmem= 4096 87380 16777216
net.netfilter.nf_conntrack_buckets=655360
net.netfilter.nf_conntrack_tcp_timeout_close_wait = 60
net.netfilter.nf_conntrack_tcp_timeout_established = 180
net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 120
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 120
net.nf_conntrack_max = 2500000